return {
  { import = "plugins.colorizer" },
  { import = "plugins.eyeliner" },
  { import = "plugins.lsp-config" },
  { import = "plugins.lualine" },
  { import = "plugins.markdown-preview" },
  { import = "plugins.neo-tree" },
  { import = "plugins.neodev" },
  { import = "plugins.nvim-autopairs" },
  { import = "plugins.nvim-cmp" },
  { import = "plugins.regex-railroad" },
  { import = "plugins.telescope" },
  { import = "plugins.todo-comments" },
  { import = "plugins.toggleterm" },
  { import = "plugins.treesitter" },
  { import = "plugins.treesitter-context" },
  { import = "plugins.vim-be-good" },
  { import = "plugins.vscode" },
}
